In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import missingno as msno

pd.set_option("display.max_columns", None)
pd.options.display.float_format = '{:,.2f}'.format

In [3]:
# On regarde comment un batiment est défini dans ce jeu de données 
building_consumption = pd.read_csv("/Users/maximebarbier/Documents/00 - Repositories/building-energy-Seattle/data/external/2016_Building_Energy_Benchmarking.csv")
building_consumption.head()

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,CouncilDistrictCode,Neighborhood,Latitude,Longitude,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),ListOfAllPropertyUseTypes,LargestPropertyUseType,LargestPropertyUseTypeGFA,SecondLargestPropertyUseType,SecondLargestPropertyUseTypeGFA,ThirdLargestPropertyUseType,ThirdLargestPropertyUseTypeGFA,YearsENERGYSTARCertified,ENERGYSTARScore,SiteEUI(kBtu/sf),SiteEUIWN(kBtu/sf),SourceEUI(kBtu/sf),SourceEUIWN(kBtu/sf),SiteEnergyUse(kBtu),SiteEnergyUseWN(kBtu),SteamUse(kBtu),Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
0,1,2016,NonResidential,Hotel,Mayflower park hotel,405 Olive way,Seattle,WA,"98,101.00",0659000030,7,DOWNTOWN,47.61,-122.34,1927,1.00,12,88434,0,88434,Hotel,Hotel,"88,434.00",NaN,NaN,NaN,NaN,NaN,60.00,81.70,84.30,182.50,189.00,"7,226,362.50","7,456,910.00","2,003,882.00","1,156,514.25","3,946,027.00","12,764.53","1,276,453.00",False,NaN,Compliant,NaN,249.98,2.83
1,2,2016,NonResidential,Hotel,Paramount Hotel,724 Pine street,Seattle,WA,"98,101.00",0659000220,7,DOWNTOWN,47.61,-122.33,1996,1.00,11,103566,15064,88502,"Hotel, Parking, Restaurant",Hotel,"83,880.00",Parking,"15,064.00",Restaurant,"4,622.00",NaN,61.00,94.80,97.90,176.10,179.40,"8,387,933.00","8,664,479.00",0.00,"950,425.19","3,242,851.00","51,450.82","5,145,082.00",False,NaN,Compliant,NaN,295.86,2.86
2,3,2016,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,Seattle,WA,"98,101.00",0659000475,7,DOWNTOWN,47.61,-122.34,1969,1.00,41,956110,196718,759392,Hotel,Hotel,"756,493.00",NaN,NaN,NaN,NaN,NaN,43.00,96.00,97.70,241.90,244.10,"72,587,024.00","73,937,112.00","21,566,554.00","14,515,435.00","49,526,664.00","14,938.00","1,493,800.00",False,NaN,Compliant,NaN,"2,089.28",2.19
3,5,2016,NonResidential,Hotel,HOTEL MAX,620 STEWART ST,Seattle,WA,"98,101.00",0659000640,7,DOWNTOWN,47.61,-122.34,1926,1.00,10,61320,0,61320,Hotel,Hotel,"61,320.00",NaN,NaN,NaN,NaN,NaN,56.00,110.80,113.30,216.20,224.00,"6,794,584.00","6,946,800.50","2,214,446.25","811,525.31","2,768,924.00","18,112.13","1,811,213.00",False,NaN,Compliant,NaN,286.43,4.67
4,8,2016,NonResidential,Hotel,WARWICK SEATTLE HOTEL (ID8),401 LENORA ST,Seattle,WA,"98,121.00",0659000970,7,DOWNTOWN,47.61,-122.34,1980,1.00,18,175580,62000,113580,"Hotel, Parking, Swimming Pool",Hotel,"123,445.00",Parking,"68,009.00",Swimming Pool,0.00,NaN,75.00,114.80,118.70,211.40,215.60,"14,172,606.00","14,656,503.00",0.00,"1,573,448.62","5,368,607.00","88,039.98","8,803,998.00",False,NaN,Compliant,NaN,505.01,2.88

In [23]:
building_consumption['Neighborhood'].nunique()

19

In [20]:
building_consumption[building_consumption["CouncilDistrictCode"] == 1]

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,Address,City,State,ZipCode,TaxParcelIdentificationNumber,CouncilDistrictCode,Neighborhood,Latitude,Longitude,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),ListOfAllPropertyUseTypes,LargestPropertyUseType,LargestPropertyUseTypeGFA,SecondLargestPropertyUseType,SecondLargestPropertyUseTypeGFA,ThirdLargestPropertyUseType,ThirdLargestPropertyUseTypeGFA,YearsENERGYSTARCertified,ENERGYSTARScore,SiteEUI(kBtu/sf),SiteEUIWN(kBtu/sf),SourceEUI(kBtu/sf),SourceEUIWN(kBtu/sf),SiteEnergyUse(kBtu),SiteEnergyUseWN(kBtu),SteamUse(kBtu),Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),DefaultData,Comments,ComplianceStatus,Outlier,TotalGHGEmissions,GHGEmissionsIntensity
59,84,2016,NonResidential,Senior Care Community,PSSA - The Mount,4831 35th Ave SW,Seattle,WA,"98,126.00",2324039001,1,SOUTHWEST,47.56,-122.38,1922,1.00,5,217603,0,217603,"Parking, Senior Care Community",Senior Care Community,"296,313.00",Parking,0.00,NaN,NaN,NaN,54.00,144.40,153.70,235.00,244.80,"42,792,072.00","45,547,252.00",0.00,"3,465,642.50","11,824,772.00","309,673.00","30,967,300.00",False,NaN,Compliant,NaN,"1,727.11",7.94
62,87,2016,SPS-District K-12,K-12 School,Arbor Heights Elementary,3701 S.W. 104th St.,Seattle,WA,"98,146.00",2518400005,1,SOUTHWEST,47.51,-122.38,1948,1.00,2,53352,0,53352,K-12 School,K-12 School,"65,568.00",NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,"176,088.09","600,813.00",0.00,0.00,False,NaN,Missing Data,NaN,4.19,0.08
81,118,2016,SPS-District K-12,K-12 School,Pathfinder K-8,1901 SW Genesee St.,Seattle,WA,"98,106.00",1324039116,1,DELRIDGE,47.56,-122.36,1999,1.00,3,74468,0,74468,K-12 School,K-12 School,"75,364.00",NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,"497,706.81","1,698,176.00",0.00,0.00,False,NaN,Missing Data,NaN,11.84,0.16
105,172,2016,Campus,University,SSCC MAIN CAMPUS,6000 16th Ave SW,Seattle,WA,"98,106.00",6171900005,1,DELRIDGE,47.55,-122.35,1970,27.00,2,441071,0,441071,College/University,College/University,"483,000.00",NaN,NaN,NaN,NaN,NaN,NaN,79.30,85.20,192.80,202.60,"38,301,744.00","41,151,732.00",0.00,"7,419,277.50","25,314,575.00","129,871.66","12,987,166.00",False,NaN,Compliant,NaN,866.23,1.96
130,214,2016,SPS-District K-12,K-12 School,Boren Building,5950 Delridge Way S.W.,Seattle,WA,"98,106.00",3438501230,1,DELRIDGE,47.55,-122.36,1963,1.00,1,145341,0,145341,K-12 School,K-12 School,"139,069.00",NaN,NaN,NaN,NaN,NaN,75.00,39.50,45.60,69.50,77.20,"5,499,097.00","6,337,972.00",0.00,"546,590.62","1,864,967.00","36,341.30","3,634,130.00",True,NaN,Error - Correct Default Data,NaN,206.01,1.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3253,49911,2016,NonResidential,Other,Educare Early Learning Center,625 S.W. 100th St.,Seattle,WA,"98,146.00",2895800030,1,DELRIDGE,47.51,-122.34,2010,1.00,2,44162,0,44162,"Parking, Pre-school/Daycare",Pre-school/Daycare,"44,162.00",Parking,"15,761.00",NaN,NaN,NaN,NaN,35.00,38.00,81.90,87.10,"1,546,484.88","1,679,541.25",0.00,"279,494.41","953,635.00","5,928.50","592,850.00",False,NaN,Compliant,NaN,38.13,0.86
3323,50044,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Junction 47,4706 California Ave SW,Seattle,WA,"98,116.00",7579200205,1,SOUTHWEST,47.56,-122.39,2015,2.00,6,271922,75134,196788,"Multifamily Housing, Parking",Multifamily Housing,"181,589.00",Parking,"70,493.00",NaN,NaN,NaN,87.00,42.30,0.00,95.00,0.00,"7,682,562.50",0.00,0.00,"1,286,695.88","4,390,206.00","32,921.17","3,292,117.00",False,NaN,Compliant,NaN,205.45,0.76
3357,50095,2016,Multifamily MR (5-9),Mid-Rise Multifamily,Broadstone Sky,4745 40th Ave SW,Seattle,WA,"98,116.00",7579200395,1,SOUTHWEST,47.56,-122.38,2015,1.00,7,208136,58818,149318,"Multifamily Housing, Parking",Multifamily Housing,"168,221.00",Parking,"44,717.00",NaN,NaN,NaN,100.00,21.10,21.10,46.90,46.90,"3,552,185.00","3,552,185.00",0.00,"582,875.62","1,988,772.00","15,634.13","1,563,413.00",False,NaN,Compliant,NaN,96.90,0.47
3370,50221,2016,Nonresidential COS,Other,High Point Community Center,6920 34th Ave SW,Seattle,WA,NaN,2524039059,1,DELRIDGE NEIGHBORHOODS,47.54,-122.37,1982,1.00,1,18261,0,18261,Other - Recreation,Other - Recreation,"18,261.00",NaN,NaN,NaN,NaN,NaN,NaN,51.00,56.20,126.00,136.60,"932,082.12","1,025,432.12",0.00,"185,334.70","632,362.01","2,997.20","299,720.00",False,NaN,Compliant,NaN,20.33,1.11
3374,50225,2016,Nonresidential COS,Mixed Use Property,South Park Community Center,8319 8th Ave S,Seattle,WA,NaN,7883603155,1,GREATER DUWAMISH,47.53,-122.32,1989,1.00,1,14101,0,14101,"Fitness Center/Health Club/Gym, Food Service, ...",Other - Recreation,"6,601.00",Fitness Center/Health Club/Gym,"6,501.00",Pre-school/Daycare,484.00,NaN,NaN,51.00,55.50,105.30,110.80,"719,471.19","782,841.31",0.00,"102,248.00","348,870.18","3,706.01","370,601.00",False,NaN,Compliant,NaN,22.11,1.57

In [4]:
building_consumption["ComplianceStatus"].value_counts()

ComplianceStatus
Compliant                       3211
Error - Correct Default Data     113
Non-Compliant                     37
Missing Data                      15
Name: count, dtype: int64

In [5]:
building_consumption["LargestPropertyUseType"].isna().sum()

np.int64(20)

In [6]:
building_consumption[building_consumption["YearsENERGYSTARCertified"].notna()]["YearsENERGYSTARCertified"].value_counts()
# la colonne outliers a beaucoup de valeur vide mais elle a toutefois son utilité. Je vais la garder pour le moment.

YearsENERGYSTARCertified
2016                                14
20172016                             8
2017                                 7
2014                                 6
20162015                             6
                                    ..
2011                                 1
20172015201420132011                 1
20152012                             1
20162015201420132012201020092008     1
20162015201020092008                 1
Name: count, Length: 65, dtype: int64

In [7]:
building_consumption["SourceEUI(kBtu/sf)"]

0      182.50
1      176.10
2      241.90
3      216.20
4      211.40
        ...
3371   161.70
3372   114.20
3373   744.80
3374   105.30
3375   115.80
Name: SourceEUI(kBtu/sf), Length: 3376, dtype: float64

In [15]:
df = building_consumption[[
    'BuildingType', 
    'PrimaryPropertyType', 
    'PropertyName', 
    'Address',
    'TaxParcelIdentificationNumber', 
    'Neighborhood',
    'ListOfAllPropertyUseTypes', 
    'LargestPropertyUseType',
    'SecondLargestPropertyUseType', 
    'ThirdLargestPropertyUseType',
#    'first_cert_year',
    'Electricity(kBtu)', 
    'NaturalGas(kBtu)', 
    'SteamUse(kBtu)',
    'SiteEUI(kBtu/sf)', 
    'SiteEUIWN(kBtu/sf)', 
    'SourceEUI(kBtu/sf)',
    'SourceEUIWN(kBtu/sf)', 
    'TotalGHGEmissions', 
    'GHGEmissionsIntensity',
    'PropertyGFATotal', 
    'NumberofBuildings',
]]

In [16]:
df

,BuildingType,PrimaryPropertyType,PropertyName,Address,TaxParcelIdentificationNumber,Neighborhood,ListOfAllPropertyUseTypes,LargestPropertyUseType,SecondLargestPropertyUseType,ThirdLargestPropertyUseType,Electricity(kBtu),NaturalGas(kBtu),SteamUse(kBtu),SiteEUI(kBtu/sf),SiteEUIWN(kBtu/sf),SourceEUI(kBtu/sf),SourceEUIWN(kBtu/sf),TotalGHGEmissions,GHGEmissionsIntensity,PropertyGFATotal,NumberofBuildings
0,NonResidential,Hotel,Mayflower park hotel,405 Olive way,0659000030,DOWNTOWN,Hotel,Hotel,NaN,NaN,"3,946,027.00","1,276,453.00","2,003,882.00",81.70,84.30,182.50,189.00,249.98,2.83,88434,1.00
1,NonResidential,Hotel,Paramount Hotel,724 Pine street,0659000220,DOWNTOWN,"Hotel, Parking, Restaurant",Hotel,Parking,Restaurant,"3,242,851.00","5,145,082.00",0.00,94.80,97.90,176.10,179.40,295.86,2.86,103566,1.00
2,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,0659000475,DOWNTOWN,Hotel,Hotel,NaN,NaN,"49,526,664.00","1,493,800.00","21,566,554.00",96.00,97.70,241.90,244.10,"2,089.28",2.19,956110,1.00
3,NonResidential,Hotel,HOTEL MAX,620 STEWART ST,0659000640,DOWNTOWN,Hotel,Hotel,NaN,NaN,"2,768,924.00","1,811,213.00","2,214,446.25",110.80,113.30,216.20,224.00,286.43,4.67,61320,1.00
4,NonResidential,Hotel,WARWICK SEATTLE HOTEL (ID8),401 LENORA ST,0659000970,DOWNTOWN,"Hotel, Parking, Swimming Pool",Hotel,Parking,Swimming Pool,"5,368,607.00","8,803,998.00",0.00,114.80,118.70,211.40,215.60,505.01,2.88,175580,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3371,Nonresidential COS,Office,Horticulture building,1600 S Dakota St,1624049080,GREATER DUWAMISH,Office,Office,NaN,NaN,"524,270.86","325,475.02",0.00,69.10,76.70,161.70,176.10,20.94,1.70,12294,1.00
3372,Nonresidential COS,Other,International district/Chinatown CC,719 8th Ave S,3558300000,DOWNTOWN,Other - Recreation,Other - Recreation,NaN,NaN,"396,546.05","553,729.98",0.00,59.40,65.90,114.20,118.90,32.17,2.01,16000,1.00
3373,Nonresidential COS,Other,Queen Anne Pool,1920 1st Ave W,1794501150,MAGNOLIA / QUEEN ANNE,"Fitness Center/Health Club/Gym, Other - Recrea...",Other - Recreation,Fitness Center/Health Club/Gym,Swimming Pool,"1,792,158.76","3,973,739.06",0.00,438.20,460.10,744.80,767.80,223.54,16.99,13157,1.00
3374,Nonresidential COS,Mixed Use Property,South Park Community Center,8319 8th Ave S,7883603155,GREATER DUWAMISH,"Fitness Center/Health Club/Gym, Food Service, ...",Other - Recreation,Fitness Center/Health Club/Gym,Pre-school/Daycare,"348,870.18","370,601.00",0.00,51.00,55.50,105.30,110.80,22.11,1.57,14101,1.00
3375,Nonresidential COS,Mixed Use Property,Van Asselt Community Center,2820 S Myrtle St,7857002030,GREATER DUWAMISH,"Fitness Center/Health Club/Gym, Food Service, ...",Other - Recreation,Fitness Center/Health Club/Gym,Pre-school/Daycare,"432,554.25","720,341.99",0.00,63.10,70.90,115.80,123.90,41.27,2.26,18258,1.00